[workspace]
resolver="2"

members = [
    "bluey",
    "bluey-web"
]

exclude = [
    "bluey-ui"
]

[patch.crates-io]
jni = { git = "https://github.com/argv-minus-one/jni-rs.git", branch = "safe-refs" }
